mybot:
# Publish all joint states --------------
 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# Publish Controllers -------------------
# 越接近末端，质量越轻，则比例需要越少，减少超调
 joint0_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint0
  pid: {p: 0.6, i: 0.1, d: 0.16}

 joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint1
  pid: {p: 0.6, i: 0.2, d: 0.1}

 joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint2
  pid: {p: 0.6, i: 0.1, d: 0.05}

 joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint3
  pid: {p: 0.45, i: 0.015, d: 0.01}

 joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint4
  pid: {p: 0.3, i: 0.01, d: 0.01}
